const pages=[...document.querySelectorAll('.page')],dots=document.querySelector('#dots'),counter=document.querySelector('#counter');let current=0,busy=false,startX=0,startY=0;
pages.forEach((_,i)=>{const d=document.createElement('i');d.className='dot';d.onclick=()=>go(i,i>current?1:-1);dots.appendChild(d)});
function ui(){counter.textContent=`${current+1} / ${pages.length}`;[...dots.children].forEach((d,i)=>d.classList.toggle('active',i===current))}
function go(n,dir){if(busy||n<0||n>=pages.length||n===current)return;busy=true;const old=pages[current],fresh=pages[n];fresh.style.transition='none';fresh.style.opacity='0';fresh.style.transform=`translateX(${dir>0?24:-24}px) scale(.985)`;fresh.classList.add('active');requestAnimationFrame(()=>requestAnimationFrame(()=>{fresh.style.transition='';fresh.style.opacity='1';fresh.style.transform='translateX(0) scale(1)';old.style.opacity='0';old.style.transform=`translateX(${dir>0?-24:24}px) scale(.985)`}));current=n;ui();setTimeout(()=>{pages.forEach((p,i)=>{if(i!==current){p.classList.remove('active');p.style=''}});busy=false},430)}
document.querySelector('#open').onclick=()=>{document.querySelector('#cover').classList.add('hidden');document.querySelector('#album').classList.remove('hidden');ui()};
document.querySelector('#next').onclick=()=>go(current+1,1);document.querySelector('#prev').onclick=()=>go(current-1,-1);
document.addEventListener('keydown',e=>{if(e.key==='ArrowRight')go(current+1,1);if(e.key==='ArrowLeft')go(current-1,-1)});
const area=document.querySelector('#pages');area.addEventListener('touchstart',e=>{const t=e.changedTouches[0];startX=t.clientX;startY=t.clientY},{passive:true});area.addEventListener('touchend',e=>{const t=e.changedTouches[0],dx=t.clientX-startX,dy=t.clientY-startY;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)*1.2)go(current+(dx<0?1:-1),dx<0?1:-1)},{passive:true});
document.querySelector('#restart').onclick=()=>{document.querySelector('#album').classList.add('hidden');document.querySelector('#cover').classList.remove('hidden')};
document.querySelector('#edit').onclick=()=>document.querySelector('#editor').classList.remove('hidden');document.querySelector('#close').onclick=()=>document.querySelector('#editor').classList.add('hidden');
document.querySelector('#save').onclick=()=>{localStorage.setItem('albumCover',document.querySelector('#coverText').value);localStorage.setItem('albumFinal',document.querySelector('#finalText').value);pages[0].querySelector('p').textContent=document.querySelector('#coverText').value;pages[7].querySelector('p').textContent=document.querySelector('#finalText').value;document.querySelector('#editor').classList.add('hidden')};ui();